### ISSUE TITLE
🐛 [Bug] The Network Gives A 504 Gate-Away Time-Out From Time To Time

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#3648]
## :bug: Bugreport

Sometimes the network gives a 504 gate-way time-out.
(Heavenly happened on XXX and the day before and in the week before as well.)

Matt and I have found that the heap size of the backend by default should be 1.5Gi.

It seems that we have to define:

```yaml
    spec:
      containers:
        resources:
          requests:
            memory: XXX
            cpu: XXX
          limits:
            memory: XXX
            cpu: XXX
```

XXX And that should be done for the Neo4j database as well where only `requests. memory` was already defined.

See:
- https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
- https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits

### Steps to reproduce the behavior

Restarted 24 time since 21.12.2019 …
But does not since 25.12.2019 …

### Expected behavior

Should not restart by error.

### Additional context

Suggestions in VSCode are:

![Bildschirmfoto 2019-12-23 um 10 25 52](https://user-images.githubusercontent.com/25344101/71555790-f3c7ab80-2a2f-11ea-80d6-19e0b1fbcaef.png)

![Bildschirmfoto 2019-12-23 um 10 25 28](https://user-images.githubusercontent.com/25344101/71555795-00e49a80-2a30-11ea-9981-fa98b27b2c04.png)

May we have to set `requests` and `limits` for web app as well!?
